- task: Docker@2
  inputs:
    containerRegistry: 'docker'
    repository: 'acrlearning'
    command: 'buildAndPush'
    image: 1.0

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"